udp_bridge/maxPacketSize: 1400
udp_bridge/remotes:
  operator:
    connections:
      default:
        topics:
          cbw_status: {source: control_by_web_status}
          sensors_flir_engine: {source: sensors/flir_engine}
          sensors_ais_contact: {source: sensors/ais/contact}
          mbr_9372_2510_margin_avg: {source: mbr/9372/2510/margin_avg}
          mbr_9372_2510_margin_min: {source: mbr/9372/2510/margin_min}
          sensors_radar_HaloA_data: {source: sensors/radar/HaloA/data}
          sensors_radar_HaloA_state: {source: sensors/radar/HaloA/state}
          sensors_radar_HaloB_data: {source: sensors/radar/HaloB/data}
          sensors_radar_HaloB_state: {source: sensors/radar/HaloB/state}
          cw4_control_drive: {source: /control/drive/virtual}
          cw4_drive: {source: /sensor/vehicle/drive}
          cw4_engine: {source: /sensor/vehicle/engine}
          posmv_position: {source: sensors/posmv/position}
          posmv_orientation: {source: sensors/posmv/orientation}
          posmv_velocity: {source: sensors/posmv/velocity}
          oem_position: {source: sensors/oem/position}
          oem_orientation: {source: sensors/oem/orientation}
          oem_velocity: {source: sensors/oem/velocity}
          pano_1_detections: {source: /sensors/cameras/pano_1/yolo4/detections}
          pano_1_camera_info: {source: /sensors/cameras/pano_1/camera_info}
          pano_2_detections: {source: /sensors/cameras/pano_2/yolo4/detections}
          pano_2_camera_info: {source: /sensors/cameras/pano_2/camera_info} 
          pano_3_detections: {source: /sensors/cameras/pano_3/yolo4/detections}
          pano_3_camera_info: {source: /sensors/cameras/pano_3/camera_info}
          pano_4_detections: {source: /sensors/cameras/pano_4/yolo4/detections}
          pano_4_camera_info: {source: /sensors/cameras/pano_4/camera_info}
          pano_5_detections: {source: /sensors/cameras/pano_5/yolo4/detections}
          pano_5_camera_info: {source: /sensors/cameras/pano_5/camera_info}
          pano_6_detections: {source: /sensors/cameras/pano_6/yolo4/detections}
          pano_6_camera_info: {source: /sensors/cameras/pano_6/camera_info}

mbr_node/radioSerialNumbers: [2510, 9442]

sonar/model: 2040
sonar/host: stormi
